function Hd = tx_filter
%TX_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 24-Aug-2017 19:08:24

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are in MHz.
Fs = 16;  % Sampling Frequency

N  = 64;         % Order
Fc = 2;          % Cutoff Frequency
TM = 'Rolloff';  % Transition Mode
R  = 0.25;       % Rolloff
DT = 'Normal';   % Design Type

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc/(Fs/2), R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
